language: java
script:
  - ./gradlew dist
  
before_deploy:
  - git config --local user.name "RealCerus"
  - git config --local user.email "m.dorn.2003@web.de"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "OCo9EP5eR1dZQfQaPF6ECIcPdyFh2DJch3Pb5GFcZUn1/28XRZgd6vaOcVTxmtkm4soFhqo4EHsq+HROKiD2uhYP8t741iX12Ic590/rFNckwecmOyP24pZng1umPx66hmkC8ezOPoAPTzSq9D9aAHaQmDt+HRv22J1oqGqCcSkkbqjjczbXjaifCgncs8S3MhMn7lkWYzZVmKJY8tnJaIyRJHDoyed+Sc7MOZk6ifFWx0vSSdB1+CuvGxhRK3qe1rxNVa+kgvD/8rDaAQ0I3iVTYq2y8tZQpcXijDcMO4Mhk5qqmbaOJ3hEGvJhgdD+bn5Be9TjPWKYQFKHXm902GxLSXEwidEk36uSny/sB8gVkfDLe3zAGhuCuECI5RET75YQCyvYO93AaIo2EekjrX8NJ4FC9smTkStRs4m6CPSJqVIRLiSb4v4yjrYo2FvwfjMPRiH1D5WPF/RQTk+boc8sl+VLtUqS7gq3ojCOt2VE3/IepknoXv19OmQAAcW6r6U9GAybbnsK32oE5mZQL/4v3eip1jBEZDEdOJyGmGpG1c5FWTxa8tRdaHwBzsc3n9xw+s/np1bgczPhohBhcbT2HImlGu7mADXbpAekkejbdytg7IQc01gJPPjLulbLxa7fy3G7WFk0ryHFZ0w+A5z9FpurSkVe116LNoLG3X0="
  file: "/desktop/build/libs/desktop-1.0.jar"
  skip_cleanup: true
