language: java
script:
  - ./gradlew dist
  
before_deploy:
  - git config --local user.name "RealCerus"
  - git config --local user.email "m.dorn.2003@web.de"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api-key:
    secure: "q8D40eYXyxVgdgV6TxhTat8vN0BNcmKIwhpNikBYGcijrmXLjnreDC3v4mj5wZ/IXKJ3Ob+9GjQZR3/zHSqBs7ywVYOgDboh79RnsjUeeZajArN9nJ+m+rEGdWPu13e54z0fEHKKGqBA8YMPuAputqGkb9ZVFCLrXqopdXtG6gSD44zGo833BgOmZuU/sL9ajVqamS59s2nGQ2x6eGJ7u//oimnCBc9algslTTkGhWrtW3qk4a5ghkrnOGdx/n/bj95F/wyHqKUYOFmUQd1wHb12HQYvaVhPqKXHYfXHATA7sYx5NFbZc/XNgRDef892Vn3Bw9CmHADrvAqx77/BcrAYiixlUzRXycenq6Nn/JKb4IHFBjvLuH8bGn6+HDS+fV+o4m59lFEdiPJnFQJ55qOSO4UMQJ3kzghOB0Ymmx/P/2HOlm5ZVa8QFzgJLQCbSgJtDgWH+27370cBgxJZd49aY3gybtp2TfbPI7b9X7sPPQESgvlMqgH1Ag781BCFwluJIRDWt9+W3ZxP0Znnbea/oVXvI9riSxOK4VoSrC3GxhgF21mzNDgQ+6U2JN8gEb0B9OBZo+d6GcDduA06UmY5dwBWmco0IMaxwWoXohgLLTw3PZst4+TPhooJ+xMrvLZ/ENt6CTGkUhCy+a7iByrpDKOJpHTZZ+4Xm6/Z5tQ="
  file: "/desktop/build/libs/desktop-1.0.jar"
  skip_cleanup: true
